_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.1
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 3
                - 13
                - 16
                - 23
                - 24
                - 55
            "4": 3.11.1
            "5": 0.19.8
            "8":
                - 2
                - 5
            "12": 0.19.8
            "13": darwin-arm64
data_source:
    value: null
model_type:
    value: null
raw_data_dir:
    value: artifact/03_19_2025_16_55_46/raw_data_ingestion/data/MetaMotion
